const pool=require('../config/db'); const HttpError=require('../utils/httpError'); const {createTrackingNumber}=require('../utils/tracking');

async function createOrder(payload){const cn=await pool.getConnection();try{await cn.beginTransaction();let subtotal=0;const resolved=[];
for(const raw of payload.items){const quantity=Number(raw.quantity);if(!Number.isInteger(quantity)||quantity<1)throw new HttpError(400,'Quantité invalide.');
const packId=Number(raw.packId||0); const articleId=Number(raw.articleId||0);
if(packId){const [[pack]]=await cn.query(`SELECT id,name,price,is_active FROM packs WHERE id=? FOR UPDATE`,[packId]);if(!pack||!pack.is_active)throw new HttpError(400,'Pack introuvable ou inactif.');const [parts]=await cn.query(`SELECT pi.article_id,pi.quantity,a.designation,a.stock_quantity FROM pack_items pi JOIN articles a ON a.id=pi.article_id WHERE pi.pack_id=? FOR UPDATE`,[packId]);if(!parts.length)throw new HttpError(400,'Pack vide.');for(const part of parts){const needed=Number(part.quantity)*quantity;if(Number(part.stock_quantity)<needed)throw new HttpError(409,`Stock insuffisant pour ${part.designation}.`);}subtotal+=Number(pack.price)*quantity;resolved.push({type:'PACK',pack,parts,quantity,unitPrice:Number(pack.price)});
}else if(articleId){const [[article]]=await cn.query(`SELECT id,designation,price,stock_quantity,is_active FROM articles WHERE id=? FOR UPDATE`,[articleId]);if(!article||!article.is_active)throw new HttpError(400,`Article ${articleId} introuvable.`);if(Number(article.stock_quantity)<quantity)throw new HttpError(409,`Stock insuffisant pour ${article.designation}.`);subtotal+=Number(article.price)*quantity;resolved.push({type:'ARTICLE',article,quantity,unitPrice:Number(article.price)});
}else throw new HttpError(400,'Article ou pack manquant.');}
const trackingNumber=createTrackingNumber();const [or]=await cn.query(`INSERT INTO orders(tracking_number,customer_name,phone,wilaya,commune,address,note,status,subtotal,delivery_fee,total) VALUES(?,?,?,?,?,?,?,'NOUVELLE',?,0,?)`,[trackingNumber,payload.customerName,payload.phone,payload.wilaya,payload.commune,payload.address,payload.note||null,subtotal,subtotal]);
for(const item of resolved){if(item.type==='ARTICLE'){await cn.query(`INSERT INTO order_items(order_id,article_id,pack_id,item_type,designation,unit_price,quantity,line_total) VALUES(?,?,NULL,'ARTICLE',?,?,?,?)`,[or.insertId,item.article.id,item.article.designation,item.unitPrice,item.quantity,item.unitPrice*item.quantity]);await cn.query('UPDATE articles SET stock_quantity=stock_quantity-? WHERE id=?',[item.quantity,item.article.id]);}else{await cn.query(`INSERT INTO order_items(order_id,article_id,pack_id,item_type,designation,unit_price,quantity,line_total) VALUES(?,NULL,?,'PACK',?,?,?,?)`,[or.insertId,item.pack.id,item.pack.name,item.unitPrice,item.quantity,item.unitPrice*item.quantity]);for(const part of item.parts){await cn.query('UPDATE articles SET stock_quantity=stock_quantity-? WHERE id=?',[Number(part.quantity)*item.quantity,part.article_id]);}}}
await cn.query(`INSERT INTO order_history(order_id,status,label,description) VALUES(?,'NOUVELLE','Commande reçue','Votre commande a été enregistrée avec succès.')`,[or.insertId]);await cn.commit();return{id:or.insertId,trackingNumber,subtotal,total:subtotal};}catch(e){await cn.rollback();throw e;}finally{cn.release();}}
async function trackOrder({trackingNumber,phone}){const [[order]]=await pool.query(`SELECT * FROM orders WHERE UPPER(tracking_number)=UPPER(?) AND phone=? LIMIT 1`,[trackingNumber,phone]);if(!order)throw new HttpError(404,'Aucune commande ne correspond à ces informations.');const [history]=await pool.query(`SELECT id,status,label,description,created_at FROM order_history WHERE order_id=? ORDER BY created_at,id`,[order.id]);const [items]=await pool.query(`SELECT id,article_id,pack_id,item_type,designation,unit_price,quantity,line_total FROM order_items WHERE order_id=? ORDER BY id`,[order.id]);return{order,items,history};}
module.exports={createOrder,trackOrder};
